export {
  Tag, Attr, Form, Lang
}

enum Tag {
  array_type = 0x01,
  class_type,
  entry_point,
  enumeration_type,
  formal_parameter,
  imported_declaration,
  label = 0x0a,
  lexical_block,
  member = 0x0d,
  pointer_type = 0x0f,
  reference_type,
  compile_unit,
  string_type,
  structure_type,
  subroutine_type = 0x15,
  typedef,
  union_type,
  unspecified_parameters,
  variant,
  common_block,
  common_inclusion,
  inheritance,
  inlined_subroutine,
  module,
  ptr_to_member_type,
  set_type,
  subrange_type,
  with_stmt,
  access_declaration,
  base_type,
  catch_block,
  const_type,
  constant,
  enumerator,
  file_type,
  friend,
  namelist,
  namelist_item,
  packed_typed,
  subprogram,
  template_type_parameter,
  template_value_parameter,
  thrown_type,
  try_block,
  variant_part,
  variable,
  volatile_type,
  dwarf_procedure,
  restrict_type,
  interface_type,
  namespace,
  imported_module,
  unspecified_type,
  partial_unit,
  imported_unit,
  condition = 0x3f,
  shared_type,
  type_unit,
  rvalue_reference_type,
  template_alias
}

enum Attr {
  sibling = 0x01,
  location,
  name,
  ordering = 0x09,
  byte_size = 0x0b,
  bit_offset,
  bit_size,
  stmt_list = 0x10,
  low_pc,
  high_pc,
  language,
  discr = 0x15,
  discr_value,
  visibility,
  import,
  string_length,
  common_reference,
  comp_dir,
  const_value,
  containing_type,
  default_value,
  inline = 0x20,
  is_optional,
  lower_bound,
  producer = 0x25,
  prototyped = 0x27,
  return_addr = 0x2a,
  start_scope = 0x2c,
  bit_stride = 0x2e,
  upper_bound,
  abstract_origin = 0x31,
  accessibility,
  address_class,
  artificial,
  base_types,
  calling_convention,
  count,
  data_member_location,
  decl_column,
  decl_file,
  decl_line,
  declaration,
  discr_list,
  encoding,
  external,
  frame_base,
  friend,
  identifier_case,
  macro_info,
  namelist_item,
  priority,
  segment,
  specification,
  static_link,
  type,
  use_location,
  variable_parameter,
  virtuality,
  vtable_elem_location,
  allocated,
  associated,
  data_location,
  byte_stride,
  entry_pc,
  use_UTF8,
  extension,
  ranges,
  trampoline,
  call_column,
  call_file,
  call_line,
  description,
  binary_scale,
  decimal_scale,
  small,
  decimal_sign,
  digit_count,
  picture_string,
  mutable,
  threads_scaled,
  explicit,
  object_pointer,
  endianity,
  elemental,
  pure,
  recursive,
  signature,
  main_subprogram,
  data_bit_offset,
  const_expr,
  enum_class,
  linkage_name
}

enum Form {
  addr = 0x01,
  block2 = 0x03,
  block4,
  data2,
  data4,
  data8,
  string,
  block,
  block1,
  data1,
  flag,
  sdata,
  strp,
  udata,
  ref_addr,
  ref1,
  ref2,
  ref4,
  ref8,
  ref_udata,
  indirect,
  sec_offset,
  exprloc,
  flag_present,
  ref_sig8 = 0x20
}

enum Lang {
  LANG_C99 = 0x000c
}
